[package]
name = "kalc-lib"
description = "a complex numbers, 2d/3d graphing, arbitrary precision, vector/matrix, cli calculator with real-time output and support for units"
license = "GPL-3.0-only"
authors = ["bgkillas <mswalhelm@gmail.com>"]
readme = "README.md"
keywords = ["cli", "calculator"]
categories = ["command-line-interface", "command-line-utilities", "mathematics"]
repository = "https://github.com/bgkillas/kalc"
rust-version = "1.85.0"
version = "1.5.0"
edition = "2024"

[features]
default=["rug", "serde", "fastnum"]
bin-deps=["dep:crossterm","dep:dirs","dep:term_size","dep:libc"]
fastnum=["dep:fastnum"]
rug=["dep:rug"]
serde=["dep:serde"]

[profile.release]
lto = true
strip = true
panic = "abort"

[profile.dev]
opt-level = 1

[dependencies]
fastrand = "2.0.2"
rug = {version="1.24.1",features = ["serde"], optional = true}
rayon = "1.10.0"
crossterm = {version= "0.29.0",optional=true}
dirs = {version="6.0.0",optional=true}
serde = { version = "1.0.219", features = ["derive"], optional = true }
fastnum = { version = "0.2.6", features = ["serde"], optional = true}

[target.'cfg(not(unix))'.dependencies]
term_size = {version="0.3.2",optional=true}

[target.'cfg(unix)'.dependencies]
libc = {version="0.2.172",optional=true}

[dependencies.gmp-mpfr-sys]
version = "1.6.5"
features = ["force-cross"]
